version: '3.8'

services:

  db:
    image: mariadb:11
    container_name: orgempresa_db_dev
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ../db/script.sql:/docker-entrypoint-initdb.d/script.sql
      - mariadb_data_dev:/var/lib/mysql

volumes:
  mariadb_data_dev: